# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
# obj-$(CONFIG_LGE_SWITCH_GPIO)	+= lge_gpio_switch.o //hoseong.kang@lge.com using lge_gpio_h2w.c 
